worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream gateway_pool {
        least_conn;
        server gateway1:8000;
        server gateway2:8000;
        server gateway3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://gateway_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-API-Key $http_x_api_key;
        }
    }
}
